default_platform(:ios)

platform :ios do
  desc "Generate App Store screenshots for iPhone 6.9\" and iPad 13\""
  lane :screenshots do
    capture_ios_screenshots
  end

  desc "Frame screenshots with device bezels (optional, requires `fastlane frameit setup` first)"
  lane :frame do
    frame_screenshots(path: "./fastlane/screenshots")
  end
end
